"""Tests for SimClient / iter_apply_kwargs.

Covers:
- iter_apply_kwargs: connect string normalization (flat pair, list of pairs,
  already-a-list passthrough, non-position commands, malformed JSON)
- SimClient.put(): a "position" command with a JSON-string connect (exactly
  what a workflow protocol block sends) actually mutates rotor_ports -
  regression test for the bug where apply() silently no-op'd on
  tuple("[[0, 2]]") instead of a real pair.
"""

from __future__ import annotations

import queue

from chemunited_core.figure_registry.rotary_valve import RotaryValveData

from chemunited_sim.cli.clock import SimClock
from chemunited_sim.cli.sim_client import SimClient, iter_apply_kwargs


class TestIterApplyKwargs:
    def test_flat_pair_string_unwrapped(self):
        calls = list(iter_apply_kwargs("position", {"connect": "[0, 2]"}))
        assert calls == [{"connect": (0, 2)}]

    def test_wrapped_single_pair_string_unwrapped(self):
        calls = list(iter_apply_kwargs("position", {"connect": "[[0, 2]]"}))
        assert calls == [{"connect": (0, 2)}]

    def test_multiple_pairs_string_fans_out(self):
        calls = list(iter_apply_kwargs("position", {"connect": "[[0, 2], [3, 4]]"}))
        assert calls == [{"connect": (0, 2)}, {"connect": (3, 4)}]

    def test_other_kwargs_preserved_across_fan_out(self):
        calls = list(
            iter_apply_kwargs(
                "position", {"connect": "[[0, 2]]", "disconnect": "", "extra": 1}
            )
        )
        assert calls == [{"connect": (0, 2), "disconnect": "", "extra": 1}]

    def test_already_a_list_passthrough_unchanged(self):
        calls = list(iter_apply_kwargs("position", {"connect": [0, 2]}))
        assert calls == [{"connect": [0, 2]}]

    def test_non_position_command_passthrough_unchanged(self):
        calls = list(iter_apply_kwargs("withdraw", {"rate": "1 ml/min"}))
        assert calls == [{"rate": "1 ml/min"}]

    def test_malformed_json_falls_back_to_passthrough(self):
        calls = list(iter_apply_kwargs("position", {"connect": "not json"}))
        assert calls == [{"connect": "not json"}]


class TestSimClientPutPositionCommand:
    def _client(self, tmp_path, component) -> SimClient:
        return SimClient(
            name=component.name,
            component=component,
            clock=SimClock(),
            cmd_queue=queue.Queue(),
            project_path=tmp_path,
        )

    def test_json_string_connect_from_workflow_block_rotates_valve(self, tmp_path):
        """Regression test: a workflow protocol's PositionParameter.connect
        arrives as a JSON string like "[[0, 2]]", exactly as generated by the
        GUI's command block. Before the fix this silently no-op'd because
        tuple("[[0, 2]]") produced a tuple of characters, not a real pair."""
        valve = RotaryValveData(name="Valve1")
        before = valve.rotor_ports
        client = self._client(tmp_path, valve)

        client.put("position", connect="[[0, 2]]", disconnect="")

        assert valve.rotor_ports != before

    def test_native_list_connect_still_works(self, tmp_path):
        valve = RotaryValveData(name="Valve1")
        before = valve.rotor_ports
        client = self._client(tmp_path, valve)

        client.put("position", connect=[0, 2])

        assert valve.rotor_ports != before

    def test_position_command_written_to_pool_log(self, tmp_path):
        valve = RotaryValveData(name="Valve1")
        client = self._client(tmp_path, valve)

        client.put("position", connect="[[0, 2]]", disconnect="")

        log_path = tmp_path / "log" / "pool" / "Valve1.jsonl"
        assert log_path.exists()
        assert '"connect": "[[0, 2]]"' in log_path.read_text(encoding="utf-8")
